### ISSUE TITLE
only scann networks with a specific tag

### ISSUE THREAD

**Issue by nikor30** [bbird81/Netbox-ipscanner#1]
Hi, like your script, can you add a function that only networks which have a special tag ?

So not all are scanned but only the ones who have ecample the tag scan.

Or other way round to exclude network with the tag exclude

Regards Niko

**Comment by bbird81** [comment]
Hi Nikor! Glad you like it :) I can definetely modify it for reading tags, I will look into it... in the meantime consider that prefixes with "Reserved" status are not scanned by the script ;)
![immagine](https://user-images.githubusercontent.com/25413624/163606711-69409ab1-fd10-4841-b357-e1089f235834.png)

BTW sorry for late reply... I'm not used to looking often in GitHub so I missed this issue, very sorry...

**Comment by nwiecz** [comment]
> Hi, like your script, can you add a function that only networks which have a special tag ?
> 
> So not all are scanned but only the ones who have ecample the tag scan.
> 
> Or other way round to exclude network with the tag exclude
> 
> Regards Niko

Hi @nikor30 

I have add the tag based scanning in the script.
Have a look in my fork ;)

Regards Nico

**Comment by bbird81** [comment]
Closing as resolved in @nwiecz fork. Kudos! :)

**Comment by lasag-2511** [comment]
> > Hi, like your script, can you add a function that only networks which have a special tag ?
> > So not all are scanned but only the ones who have ecample the tag scan.
> > Or other way round to exclude network with the tag exclude
> > Regards Niko
> 
> Hi @nikor30
> 
> I have add the tag based scanning in the script. Have a look in my fork ;)
> 
> Regards Nico

@nwiecz : Does the tag based scanning works for you ? I have the below error. Also can we name of the Tag based on our choice? Can you please suggest. Thanks 

``` Script file at: /opt/netbox/netbox/scripts/ipscanner.py could not be loaded ```
