### ISSUE TITLE
 dns names not getting populated - netbox version 3.6

### ISSUE THREAD

**Issue by lasag-2511** [bbird81/Netbox-ipscanner#10]
> > Hi does scan of Ips work ? can you please suggest ?
> 
> Yes it does work, many people (and myself) use it successfully.

with the new versions of netbox v3.6.0, the dns names are not getting populated to the netbox, @bbird81 : could you please assist

**Comment by r-lindner** [comment]
Does the old script without my changes work?
https://raw.githubusercontent.com/bbird81/Netbox-ipscanner/0e52f86c5622d16ae893538e765402bb46c451f2/netbox_ipscanner.py

**Comment by lasag-2511** [comment]
> Does the old script without my changes work? https://raw.githubusercontent.com/bbird81/Netbox-ipscanner/0e52f86c5622d16ae893538e765402bb46c451f2/netbox_ipscanner.py

no it doesnot work either

**Comment by bbird81** [comment]
@r-lindner I don't think that your changes broke something, it's just a `.lower()`...

@lasag-2511 you need to be a little more specific if you want us to help you.

- did you set DNS correctly on the host running Netbox?
- Does _dig_ resolves names correctly from the shell?
**(my guess is no on these two above)**
- Is there any error in the console?

I personally don't think it's 3.6 related, I don't see any broking changes in the API that explains why it doesn't work.

You might want to add a couple `self.log_warning(..)` around lines 70something to see what's going on with the values of variables.

**Comment by lasag-2511** [comment]
> @r-lindner I don't think that your changes broke something, it's just a `.lower()`...
> 
> @lasag-2511 you need to be a little more specific if you want us to help you.
> 
> * did you set DNS correctly on the host running Netbox?
> * Does _dig_ resolves names correctly from the shell?
>   **(my guess is no on these two above)**
> * Is there any error in the console?
> 
> I personally don't think it's 3.6 related, I don't see any broking changes in the API that explains why it doesn't work.
> 
> You might want to add a couple `self.log_warning(..)` around lines 70something to see what's going on with the values of variables.

sorry, its my mistake, after reboot dns name resolution disappeared. I made permanent changes and now i can see dns names populated. Thank you
