### ISSUE TITLE
Script tested on later versions of NetBox

### ISSUE THREAD

**Issue by bep6vaku** [bbird81/Netbox-ipscanner#15]
Is this script validated to run on netbox v 3.7.8? I followed the instructions and uploaded to the /opt/netbox/scripts but nothing happens. Is this an automatic process to scan a configured prefix or is there a manual process?

**Comment by bbird81** [comment]
Hi,
nope, not tested; anyway it must be launched manually (or scheduled) from the script section of Netbox
