### ISSUE TITLE
Issue with Script

### ISSUE THREAD

**Issue by stroes** [bbird81/Netbox-ipscanner#3]
```
An exception occurred: RequestError: The request failed with code 406 Not Acceptable

Traceback (most recent call last):
  File "/opt/netbox-3.4.2/netbox/extras/scripts.py", line 464, in _run_script
    script.output = script.run(data=data, commit=commit)
  File "/opt/netbox-3.4.2/netbox/scripts/netbox_ipscanner.py", line 30, in run
    subnets = nb.ipam.prefixes.all()
  File "/opt/netbox/venv/lib/python3.10/site-packages/pynetbox/lib/endpoint.py", line 121, in all
    for i in req.get()
  File "/opt/netbox/venv/lib/python3.10/site-packages/pynetbox/lib/query.py", line 240, in get
    return req_all(self.url)
  File "/opt/netbox/venv/lib/python3.10/site-packages/pynetbox/lib/query.py", line 222, in req_all
    req = make_request(url)
  File "/opt/netbox/venv/lib/python3.10/site-packages/pynetbox/lib/query.py", line 219, in make_request
    raise RequestError(req)
pynetbox.lib.query.RequestError: The request failed with code 406 Not Acceptable
```

Hi there, really like the idea of your script. Testing it out at the moment to see if i can make my life a little bit easier but i am getting this error when trying to run it. 

Any ideas why i would get this? Sorry my python knowledge is very limited.

**Comment by bbird81** [comment]
Hi :) let's see if we can sort it out...

Problem seems to arise from line 30:
subnets = nb.ipam.prefixes.all()

This call basically leverages Netbox API using the pynetbox library to get the list on CIDR prefixes that are then ping-scanned in the following for cycle.
'406 Not Acceptable' as an answer means that the request is somehow malformed, but that's strange since this call uses the embedded pynetbox library... first, let's make sure you did the basic stuff: did you create an API token in Netbox and put it in line 4 of script? Did you also put your resolvable netbox fqdn in line 28 of script?

If you did those two things, please let me know the version of Netbox you are running, so that I can check if anything has changed on that library in recent releases.

**Comment by stroes** [comment]
> Hi :) let's see if we can sort it out...
> 
> Problem seems to arise from line 30: subnets = nb.ipam.prefixes.all()
> 
> This call basically leverages Netbox API using the pynetbox library to get the list on CIDR prefixes that are then ping-scanned in the following for cycle. '406 Not Acceptable' as an answer means that the request is somehow malformed, but that's strange since this call uses the embedded pynetbox library... first, let's make sure you did the basic stuff: did you create an API token in Netbox and put it in line 4 of script? Did you also put your resolvable netbox fqdn in line 28 of script?
> 
> If you did those two things, please let me know the version of Netbox you are running, so that I can check if anything has changed on that library in recent releases.

Thanks so much for replying, much appreciated. I realized the version of pynetbox in the `local_requirements.txt` was not specified and it defaulted to installing `3.4.2` i changed this to `pynetbox==7.0.0` and suddenly everything started working properly.

**Comment by bbird81** [comment]
No problem, thanks for raising the issue, it's key to improve :)

That's what I was thinking (i.e. that there was some sort of version mismatch between pynetbox and Netbox) but I didn't want to jump to conclusion (hence the request of your version of Netbox).

On [pynetbox](https://github.com/netbox-community/pynetbox) doc is stated that:
> Note: Version 6.7 and later of the library only supports NetBox 3.3 and above.

I currently run pynetbox 6.6.1 and Netbox 3.4.1 in my environment and it works, but I probably should upgrade the library.

Thanks again for pointing out the issue, glad you solved it! Enjoy the script! :)
